# Generated by Django 3.1.7 on 2021-05-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('normally', models.CharField(max_length=100)),
                ('permanence', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('account_classification', models.IntegerField()),
                ('contra', models.BooleanField()),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True)),
                ('me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.child_account')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.child_account')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('purchasing_price', models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True)),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.child_account')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Sub_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('root_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.account_group')),
            ],
        ),
    ]
