# Generated by Django 3.1.7 on 2021-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_group',
            options={'verbose_name': 'Account Group', 'verbose_name_plural': 'Account Groups'},
        ),
        migrations.AlterModelOptions(
            name='account_sub_group',
            options={'verbose_name': 'Account Sub-Group', 'verbose_name_plural': 'Account Sub-Groups'},
        ),
        migrations.AlterModelOptions(
            name='child_account',
            options={'verbose_name': 'Child Account', 'verbose_name_plural': 'Child Accounts'},
        ),
        migrations.AlterModelOptions(
            name='inventory_item',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
    ]
