# Generated by Django 3.1.7 on 2021-05-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210512_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child_account',
            name='account_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.account_sub_group'),
        ),
    ]
