# Generated by Django 3.1.7 on 2021-05-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210513_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_account',
            name='description',
        ),
    ]
