# Generated by Django 3.1.7 on 2021-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_child_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
