# Generated by Django 3.1.7 on 2021-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_child_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_sub_group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
