# Generated by Django 3.1.7 on 2021-05-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_sub_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Normally_Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normally', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=5, max_digits=24, null=True)),
                ('child_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.child_account')),
            ],
        ),
    ]
