# Generated by Django 3.1.7 on 2021-05-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210513_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='normally_journal',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.journal'),
        ),
    ]
