# Generated by Django 3.1.7 on 2021-05-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_normally_journal_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='journal',
            new_name='code',
        ),
    ]
