# Generated by Django 3.1.7 on 2021-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210513_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Normally_Journal',
            new_name='Journal_Entries',
        ),
    ]
