# Generated by Django 3.1.7 on 2021-05-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210515_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entries',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=24, null=True),
        ),
    ]
